Remove connection-specific headers from HTTP/2 message.
eset/grpc-rest-proxy pull request #7
Opened 2024-08-12 09:35 UTC by luborco

2024-08-12 14:00 UTC, MartinKuzma requested changes

2024-08-12 14:00 UTC, MartinKuzma commented on pkg/transport/transport.go
> +		fmt.Fprint(w, protojson.Format(rpcResponse))
Don't use Fprint for copying data to writer. io.copy or w.Write are better options.

2024-08-12 14:00 UTC, MartinKuzma commented on pkg/service/transformer/transformer.go
> +func GetRPCRequestContext(protoMajor int, request *http.Request) context.Context {
Doesn't require protoMajor argument. Protomajor is already present in request.

2024-08-12 14:00 UTC, MartinKuzma commented on pkg/service/transformer/transformer.go
> +		if protoMajor > 1 && isConnectionSpecificHeader(name) {
This is incorrect place for checking name. For each value you are doing same name check. Instead, move this check above for loop.

2024-08-13 11:03 UTC, danielkraic commented on pkg/service/transformer/transformer.go
> +func setHeader(headers http.Header, protoMajor int, name string, values []string) {
Optional: Move this function to the bottom of the file.

It is not required in Go to define a function before this function is used. Best practice for more readable code is to define exported functions first and then un-exported functions. Files are meant to be read from top to bottom, not the opposite way. Therefore the more important functions (exproted) should be defined before less important functions.

2024-08-13 11:46 UTC, MartinKuzma approved these changes

2024-08-13 11:51 UTC, merged